[project]
name = "tg-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram>=3.22.0",
    "aiosqlite>=0.21.0",
    "dotenv>=0.9.9",
]
